### ISSUE TITLE
aircraft.cfg split

### ISSUE THREAD

**Issue by thealx-eech** [klasbj/planeconverter#3]
Maybe it's worth to split legacy file on categories like it works in 2020, with adding missing required parameters like engine power/thrust and modern electrics, as so much questions appear "why my plane does not move".

**Comment by DSMTurboAWD** [comment]
@thealx-eech Do we know which legacy model types/categories for sure do not work?
This app mainly JSON serializes the old textures and reconfigures the pathing for the old FSX files to the NEW MSFS layout.

It might be possible to do what you are saying, but the program would have to know what each airplane requires to work, and look for those specific parameters, which is different with each aircraft....

**Comment by klasbj** [comment]
I think it's quite difficult to do much automatic conversion, at least given what I know at this point. Then again, I only looked at it for a few days before giving up on my efforts :smile:

Currently it only does the bare minimum to package old aircraft for in the new package format. If there are specific things that has to be done to all/most conversions, I think it's fair game to try to add them, but I didn't really find that in my experimentation.

BTW, thanks for your contributions, both of you!

**Comment by OzWookiee** [comment]
Some of the biggest data though is in the AIR file so you would need to read that in, interpret it and then place it in the appropriate CFG FIRST before moving any CFG data. Data in original aircraft.cfg had priority over same data in AIR file.

**Comment by DSMTurboAWD** [comment]
I am not sure we can dig into the AIR files, as they are binaries, and likely (copyright) protected, so digging into them might be frowned upon. 
I can't say for sure, as I do not do much of the 3d modeling stuff. But copying over the JSON stuff is probably 'good enough' to get folk started.
