### ISSUE TITLE
The project file cannot be loaded

### ISSUE THREAD

**Issue by ayyucedemirbas** [klasbj/planeconverter#6]
I'm trying to open the .sln file with Visual Studio 2017 and I get this error message:

![image](https://user-images.githubusercontent.com/8023150/96039184-f1c0c300-0e70-11eb-9a62-8dcc7cd9653f.png)

**Comment by klasbj** [comment]
Visual Studio 2017 does not support .NET Core 3.1, you need Visual Studio 2019 for that.

Alternatively you can build using the `dotnet` command line utility.
